
export const LOGIN_PAYMENT_USER_SUCCESS = 'LOGIN_PAYMENT_USER_SUCCESS'
export const LOGIN_PAYMENT_USER_FAIL = 'LOGIN_PAYMENT_USER_FAIL'

export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN'
export const SET_CLEAR_LOGIN = 'SET_CLEAR_LOGIN'
export const SET_LOGIN = 'SET_LOGIN'